# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vw6bLWpsoNe9Y8qNcQB2x2ojS11BfT1h

Exercicio 1
"""

class Quadrado():
  def __init__(self, lado):
    self.setLado(lado)
  def setLado(self, lado):
    self.lado = lado
  def getLado(self):
     return self.lado
  def area(self):
     return self.lado*self.lado
     print(area)
  def comprimento(self):
    return self.lado*2
    print(comprimento)


Nu1=int(input('Digite um Lado: '))
q=Quadrado(Nu1)
print('A area é :',q.area(),'m²')
print('O comprimento é : ',q.comprimento())

"""**EXERCICIO 2**

"""



class Retangulo():
  def __init__(self, comprimento, largura):
    self.setComprimento(comprimento)
    self.setLargura(largura)

  def setComprimento(self, comprimento):
      self.comprimento = comprimento
  def setLargura(self, largura):
       self.largura = largura
  def getComprimento(self):
       return self.comprimento
  def getLargura(self):
      return self.largura
  def area(self):
      return self.comprimento * self.largura
  def perimetro(self):
              return (2 * self.comprimento) + (2 * self.largura)

              
comp = float(input('Informe o valor do comprimento: '))
larg = float(input('Informe o valor da largura: '))

r = Retangulo(comp,larg)
print("A area é: ", r.area())
print("O perimetro é: ", r.perimetro())