# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16lDgHeCNKNB_zc0ekmfIQd82eSEsy1ae

**Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.**
"""

##ENTRADA DO USUARIO EXERCICIO 1

nota = float(input("insira uma Nota De 0 a 10: "))

##LAÇO DE REPETIÇÃO.SE NOTA FOR FALSA PEÇA NOTA NOVAMENTE

while (nota < 0) or (nota > 10):
    nota=float(input("Nota Invalida. Nota Não Pode ser Menor que 0 e maior que 10 \n Tente Novamente! "))
##Caso Nota Seja Valida Informe na Tela

print("Nota Valida!")

"""**Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.**"""

print("Informe seu Login e Senha: ")
Login=input("Usuario:   ")
senha=input("Login: ")
while Login == senha :
  print("Senha não Pode ser Igual Login")
  Login=input("Cadastre uma Senha ")
print("Cadastro Concluido Com Sucesso! ")

"""***Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento. ***"""

popuA=int(input("População do país A: "))
while popuA<0:
    popuA=int(input("População do país deve ser maior que 0: "))
taxaA=float(input("Taxa de crescimento da cidade A: "))

popuB=int(input("População do país B: "))
while popuB<0:
    popB=int(input("População do país deve ser maior que 0: "))
taxaB=float(input("Taxa de crescimento da cidade B: "))

ano=0
while popuA < popuB:
    ano += 1
    popuA = int((1 + (taxaA/100) )* popuA)
    popuB = int((1 + (taxaB/100) )* popuB)
    print("Ano %d:" % ano)
    print("Populaçao A: %d" % popuA)
    print("População B: %d\n\n" % popuB)

print("O número de anos para a população A igualar ou ultrapssar a população B é:",ano)

"""**Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50**"""

for n in range(1,50,2):
    print(n)

"""**O Departamento Estadual de Meteorologia lhe contratou para desenvolver um programa que leia as um conjunto indeterminado de temperaturas, e informe ao final a menor e a maior temperaturas informadas, bem como a média das temperaturas.**"""

n_temperaturas  =  int ( input( "Quantidade de temperaturas que irá digitar: " ))
temperaturas  = []
n_temperatura  =1
for  temperatura  in  range( n_temperaturas ):
    print( "Temperatura n°" , n_temperatura)
    temperatura  =  temperaturas.append( float( input( "Digite a temperatura: " )))
    n_temperatura  +=  1
print( "Maior temperatura = " , max ( temperaturas ))
print( "Menor temperatura = " , min ( temperaturas ))
print( "Média = " , round (sum( temperaturas ) /  len( temperaturas ), 2 ))

"""
****Faça um programa que leia o código dos itens pedidos e as quantidades desejadas. Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.****

"""

print('================================= \n| COD |     PRODUTO     | VALOR | \n| 100 | Cachorro quente | 1,20R$| \n'
      '| 101 | Bauru Simples   | 1,30R$|\n| 102 | Bauru com ovo   | 1,50R$|\n| 103 | Hamburguer      | 1,20R$| \n'
      '| 104 | Chessburguer    | 1,70R$|\n| 105 | Suco            | 2,20R$| \n| 106 | Refrigerante    | 1,00R$|\n'
      '=================================\n Para sair digite 0')

menu = {

    '100': ['Cachorro quente', 1.20],
    '101': ['Bauru Simples', 1.30],
    '102': ['Bauru com ovo', 1.50],
    '103': ['Hamburguer', 1.20],
    '104': ['Chessburguer', 1.70],
    '105': ['Suco', 2.20],
    '106': ['Refrigerante', 1.00]
}

pedido = {}
while True:
    codigo = input('Informe o codigo: ')
    if (codigo == '0'):
        break
    if codigo in menu:
        quantidade = int(input('Informe a quantidade: '))
        if quantidade > 0:
            valorItem = menu.get(codigo)
            pedido.update({codigo: (valorItem, quantidade)})

valorDoPedido = 0

for linha in pedido.items():
    valorDoPedido += linha[1][0][1] * linha[1][1]  # Preço * Quantidade

print('\nSEU PEDIDO: ')

for linha in pedido.items():
    print(str(linha[1][1]) + ' x ' + 'R$ ' + str(round(linha[1][0][1], 2)) + ' --- ' + str(linha[1][0][0]))

print('\nTOTAL DO PEDIDO: R$ ' + str(round(valorDoPedido,2)))

"""**Em uma competição de ginástica, cada atleta recebe votos de sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica sendo a média dos votos restantes. Você deve fazer um programa que receba o nome do ginasta e as notas dos sete jurados alcançadas pelo atleta em sua apresentação e depois informe a sua média, conforme a descrição acima informada (retirar o melhor e o pior salto e depois calcular a média com as notas restantes). As notas não são informados ordenadas. Um exemplo de saída do programa deve ser conforme o **exemplo abaixo: 
**Atleta: Aparecido Parente**
Nota: 9.9
Nota: 7.5
Nota: 9.5
Nota: 8.5
Nota: 9.0
Nota: 8.5
Nota: 9.7

**Resultado final:**
Atleta: Aparecido Parente
Melhor nota: 9.9
Pior nota: 7.5
Média: 9,04. 
"""

nome_atleta=True
n_atleta=1
while nome_atleta !=" ":
    notas = []
    print( " \n " *5 )
    print( "Atleta n°" ,n_atleta )
    nome_atleta  =  input( "Digite o nome do atleta: " )
    if  nome_atleta=='' :
        break
    else:
        n_jurado=  1
        print( " \n "  *  3 )
        for  n_jurado  in  range( 7 ):
            print( "Jurado n°" , n_jurado )
            nota  =  float ( input ( "Digite uma nota: " ))
            notas.append( nota )
            n_jurado  +=  1
        print ( "Atleta: " , nome_atleta )
        n_jurado  =  1
        contagem  =  0
        for  contagem  in  range( 7 ):
            print( n_jurado , "° Jurado : " , notas [ contagem ])
            n_jurado  +=  1
            contagem+=  1
        print ( "Resultado Final:" )
        print ( "Nome do atleta: " , nome_atleta )
        print ( "Melhor nota: " , max ( notas ))
        print ( "Pior nota: " , min ( notas ))
        notas.remove( max( notas ))
        notas.remove( min( notas ))
        media=sum( notas ) /  len( notas )
        print ( "Media: " , round( media , 2 ))
        n_atleta+=1