# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-jlo9Yc9DATpAKE_Za6FNfxsL4owMYv
"""



"""**Exercicio 1**

"""

print("Olá Mundo!")

"""**Exercicio 2**"""

Num1=input("Digite Um Numero: ")
print("O numero Informado é :",Num1)

"""**Exercicio 3**"""

Num2=int(input("Digite um Numero: "))
Num3=int(input("Digite um Segundo Numero: "))
Soma=Num2+Num3
print("O Resultado Dos Dois Numero: ",Num2,"+",Num3,"=",Soma)

"""**Exercicio 4**

"""

Nota1=int(input("Digite a 1º Primeira Nota: "))
Nota2=int(input("Digite a 2º Nota: "))
Nota3=int(input("Digite a 3º Nota: "))
Nota4=int(input("Digite a 4º Nota: "))

Soma=Nota1+Nota2+Nota3+Nota4
Divi=Soma/4

print("Sua Media De Nota É: ",Divi)

"""**Exercicio 5**"""

from typing import Collection
print("COMPRIMENTO")
Metro=int(input("INFORME O METRO: "))
Resultado=Metro*100
print(Metro,"METRO É IGUAL HÁ: ",Resultado,"CENTIMETRO")

"""**Exercicio 6**"""

import math

raio= float(input("Informe um raio de um circulo: "))
area= math.pi*(raio ** 2)
print("A área é de:", area)

"""**Exercicio 7**"""

Lado=float(input("Informe um lado do Quadrado: "))
Area=Lado * Lado
Dobro=Area * 2
print ("A area do Quadrado é :",Area,"O Dobro Desta Area é : ",Dobro)

"""**Exercicio 8**

"""

ValorHora=float(input("Qual Valor Da Hora Trabalhada: "))
HorasMes=float(input("Total de Horas nO Mês: "))
Salario= ValorHora * HorasMes
Resultado= round (Salario * 30,2)
print("Total A Receber Por Mês: ",Resultado)

"""**Exercicio 9**"""

F=float(input("Informe o Valor De Graus em fahrenheit: "))
C=(F-32 )*(5/9)
print("Valor em Celsius: {0}°C".format(C))

"""**Exercicio 10**"""

C = float(input("Entre com a temperatura em graus Celsius: "))
   F = C * (9 / 5) + 32,
   print('Valor em Fahrenheit: {0}°F'.format(F))

"""**Exercicio 8**"""

# Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre:
# o produto do dobro do primeiro com metade do segundo .
# a soma do triplo do primeiro com o terceiro.

PrimeiroNum = int(input("Informe um numero inteiro: "))
SegundoNumero=int(input("Informe o Segundo Numero: "))
NumeroReal=float(input("Informe um Numero Real: "))
print("O produto do dobro do primeiro com metade do segundo: ",(PrimeiroNum*2)*(SegundoNumero/2))
print("A soma do triplo do primeiro com o terceiro",(PrimeiroNum*3)+NumeroReal)
print("O terceiro Elevado ao Cubo: ", NumeroReal**3 )

"""**Exercicio 12**"""

Altura=float(input("Informe a Sua Altura: " ))
print("Seu Peso Ideal é: ",round((72.7*Altura)-58),"Kg")

"""**Exercicio 13**"""

# Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
# Para homens: (72.7*h) - 58
# Para mulheres: (62.1*h) - 44.7
print(" Calcule Seu Peso Ideal: ")

Alt=float(input("Digite a Sua Altura: "))
print("Peso ideal para homens: ",round((72.7*Alt) - 58,2))
print("Peso ideal para Mulheres: ",round((62.1*Alt) - 44.7,2))

"""**Exercicio 14**"""

# João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o
# Estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. 
# João precisa que você faça um programa que leia a variável peso (peso de peixes) e
# calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar.
# Imprima os dados do programa com as mensagens adequadas.


Limite=50
Excesso=0
Multa_por_quilo=4
Peso=float(input("Digite o peso Total dos Peixe: "))

if Peso>Limite:
   Excesso=Peso-Limite
   Multa=Excesso*Multa_por_quilo
   print("Peso Acima do Limite de : ",Limite,"kg. Multado em R$ ",Multa,"Pelo Excesso de ",Excesso,"Kg")

else:
     print("Peso Abaixo do Limite: ",Limite,"kg.")

"""**Exercicio 15**

"""

# Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês,
# sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
# salário bruto.
# quanto pagou ao INSS.
# quanto pagou ao sindicato.
# o salário líquido.
# calcule os descontos e o salário líquido, conforme a tabela abaixo:
# + Salário Bruto : R$
# - IR (11%) : R$
# - INSS (8%) : R$
# - Sindicato ( 5%) : R$
# = Salário Liquido : R$
# Obs.: Salário Bruto - Descontos = Salário Líquido.




ValorHora=float(input("Qual Valor Da Hora Trabalhada : "))
HorasMes=float(input("Total de Horas no Mês: "))
HorasMinuto=int(input("Informe  o   total de Minutos Trabalhado no Mês : "))

Minutos_em_Decimal=round(HorasMinuto/60,2)

Salario_Bruto=round((HorasMes+Minutos_em_Decimal)*ValorHora,2)

Ir=round(Salario_Bruto * 11/100,2)
Inss=round(Salario_Bruto * 8/100,2)
Sindicato=round(Salario_Bruto * 5/100,2)

print("Salario Bruto: ",Salario_Bruto)
print("Ir [11%]:",Ir)
print("INSS [8%]: ",Inss)
print("Sindicato [5%]: ",Sindicato)
print("Valor Liquido a Receber: ",Salario_Bruto-Ir-Inss-Sindicato)

"""**Exercicio 16**


"""

#Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada.
#Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00.
#Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total.

CoberturaTinta=3
CapacidadeLata=18
PrecoLata=80.0
TamanhoArea=float(input("Digite o Tamanho da aréa a Ser Pintada(em m²): "))

Litros=TamanhoArea/CoberturaTinta
LatasInteira=int(Litros/CapacidadeLata)
if(Litros%CapacidadeLata!=0):
  LatasInteira +=1
  ValorTotal=LatasInteira*PrecoLata

  print("Quantidade de litros de tinta necessários ",Litros)
  print("Quantidade de latas de tinta necessário: ",LatasInteira)
  print("Valor Total da Compra: ",ValorTotal)

"""**Exercicio 17**"""



Area=float(input("Informe a area(em m²)a ser pintada: "))
Litros1=Area/6
Quantidade1=Litros1/3.6
if (Quantidade1 !=int(Quantidade1)):
    Quantidade1= int (Quantidade1)+1
    Custo1=Quantidade1 * 25
    print("Comprando apenas Galões de 3.6 litros a quantidade será ",Quantidade1,"e o Valor Total Será: ",Custo1)
else:
      Custo1=Quantidade1 * 25
      print("Comprando apenas Galões de 3.6 litros a quantidade será ",Quantidade1,"e o Valor Total Será: ",Custo1)
Quantidade2=Litros1/18
if(Quantidade2 !=int(Quantidade2)):
  Quantidade2=int(Quantidade2)+1
  Custo2=Quantidade2 * 80
  print("Comprando apenas Galões de 18 litros a quantidade será ",Quantidade2,"e o Valor Total Será: ",Custo2)
else:
  Custo2=Quantidade2 * 80
  print("Comprando apenas Galões de 18 litros a quantidade será ",Quantidade2,"e o Valor Total Será: ",Custo2)

resto=Litros1 % 18
Quantidade3=resto/3.6
if (Quantidade3 != int(Quantidade3)):
   Quantidade3=int(Quantidade3)+1
   Custo3=Quantidade3 * 25
   print("Comprando apenas Galões de 3,6 litros a quantidade será: ",Quantidade3,"e o Custo Será: ",Custo3)
Quantidade4=Litros1//18
Custo4=Quantidade4 * 80
Folga=(Custo3+Custo4)* 0.1
Ct = (Custo3+Custo4)-Folga
print("Misturando Galões e Latas se Obtem: ",Quantidade3," De Galões e ",Quantidade4,"LatasTintas")
print("O custo total é: ",Ct)

"""**Exercicio 18**"""

print("**********CALCULO DE TEMPO**********")
Mb=int(input("Informe o Tamanho do arquivo em MB que deseja fazer Download: "))
Link=int(input("Qual velocidade do seu Link em Mbps: "))
Tempo=(Mb/(Link/8))/60

print(f"Para efetuar um Download de {Mb} MB com a Velocidade de : {Link} Mbps, irá demorar {Tempo:.0f} minutos")