# -*- coding: utf-8 -*-
"""ATIVIDADE 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYD1WW-oALggidNvS0g0OxGSj1GYpU8_

#**Faça um Programa que Leia Um Vetor de 5 numeros inteiros e mostre_os**
"""

cont=0
total = []
while cont<=4:
 Num1=int(input("Digite um Numero Inteiro: "))
 total.append(Num1)
 cont+=1
print(total)

"""2

"""

cont=0
total = []
while cont<=4:
 Num1=float(input("Digite um Numero Inteiro: "))
 total.append(Num1)
 cont+=1
print(total)

"""**Exercicio 2**

# **.Faça um Programa que leia um vetor de 10 números reais e mostre-os na ordem inversa.**
"""

cont=9
total = []
while cont>=0:
 Num1=float(input("Digite um Numero Inteiro: "))
 total.append(Num1)
 cont=cont-1
print(total)
cont=9
while cont>=0:
  print(total[cont])
  cont=cont-1

"""### **Exercicio 3**

# **Faça um Programa que leia 4 notas, mostre as notas e a média na tela.**
"""

cont=0
soma=[]
for cont in range(1,5):
  Nota=float(input("Digite a Nota: "))
  soma.append(Nota)
  cont=+1
print("Media Total:",sum(soma)/len(soma))



"""# **`Exercicio 4`**
# **Foram anotadas as idades e alturas de 30 alunos. Faça um Programa que determine quantos alunos com mais de 13 anos possuem altura inferior à média de altura desses alunos.**
"""

alt=[1.70,1.60,1.75,1.60,1.70,1.78,1.84,1.40,1.10,1.05,1.25,1,1.30,1.48,1.55,1.60,1,75,1.65,1.64,1.63,1.38,1.45,1.42,1.33,1.44,1.20,1.77,1.63,1.49,1.55]
idade=[12,13,10,28,13,14,17,15,7,10,17,16,17,18,12,15,13,10,8,66,28,22,35,22,28,27,32,50,10]

Media_alt=sum(alt)/ len(alt)

Cont=0
quant=0
while Cont < len(idade):
  if(idade [Cont]> 13 and alt [Cont]< Media_alt):
    quant+=1
  Cont+=1
print("O numero de Alunos Maior que 13 anos e com Media De altura Inferior a Media Da Turma: ",quant)

"""# **Exercicio 5**
# **Uma feira possui a seguinte tabela de preços de frutas
:CódigoPreço Unitário

BananaR$4,00
LaranjaR$3,50
LimãoR$10,00
MaçaR$6,50
MangaR$7,00
MorangoR$8,50
TangerinaR$5,50
UvaR$12,00

**Escreva um programa que cria um dicionário a partir da tabela acima onde as chaves são os nomes das frutas e os valores são os seus respectivos preços por Kg. Em seguida, crie uma lista de tuplas, onde cada tupla possui o formato(<fruta>, <quantidade_em_kg>), simulando uma lista de compras. Caso uma fruta desejada da lista não esteja disponível na tabela, o programa deve imprimir uma mensagem dizendo"Fruta indisponivel: <nome_da_fruta>". Para todas as outras frutas disponíveis, o programa deve calcular o valor total da compra e imprimir uma mensagem com o valor final.**

"""

Sacolao={"banana":4,
                   "Laranja":3.5,
                   "limao":10,
                   "manga":7,
                   "morango":8.50,
                   "tangerina":5.5,
                   "uva":12}
carrinho=[("morango",20),("uva",10)]
valor_total=0.0;
for fruta,quantidade in carrinho :
  if fruta in Sacolao:
    valor_total +=valor_total+(quantidade*Sacolao[fruta])
  else:
   print("Frutas indisponivel: "+fruta)
print(valor_total)

"""**Exercicio 4**
# **Foram anotadas as idades e alturas de 30 alunos. Faça um Programa que determine quantos alunos com mais de 13 anos possuem altura inferior à média de altura desses alunos.**
"""

# aqui testei apenas para 7 alunos
idades = [10,27,19,22,89,17,14]
alturas = [1.60,1.23,1.76,1.98, 1.22,1.46,1.10]

mediaAltura = sum(alturas)/len(alturas)

quantidadeAlunos = 0
for i in range(1, len(idades)):
    if idades[i] > 13 and alturas[i] < mediaAltura:
        quantidadeAlunos = quantidadeAlunos + 1

print (str(quantidadeAlunos) + " alunos possuem mais de 13 anos e altura inferior a  media de altura dos alunos")