# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ORAXhZ8zYYE6FcfrqsxbWrJbJtylzNw

A. Atributos tipo String não podem receber valores None ou String vazia

B. Implementar Construtor(__init__) que recebe valores para todos os atributos da classe 


C. Implementar um main que criado is objetos:


um do tipo Cachorro e outro do tipo Cachorro Adestrado.Ao final,deve-se imprimir os dadosdos objetos criados fazendo chamadas ao método__str__ **negrito**
"""

class Cachorro():

  def __init__(self,nome,raca):
    self.__nome = nome
    self.__raca = raca
    
  def setNome(self,valor):
    self.__nome= valor

  def getNome(self):
    return self.__nome

  def setRaca(self,valor):
    self.__raca=valor
    

  def getRaca(self):
    return self.__raca

  def latir():
    print("AU AU")
  
  def Comer():
    print("Cachorro comendo ")
  
  def __str__(self):
    return "Nome Cachorro : " + self.__nome + "A Raça: "+self.__raca


class Cachorro_Adrestado(Cachorro):
  def __init__(self,nome,raca):
    super().__init__(nome,raca)

  def Deitar(self):
    print("Cachorro Deitar ")
  
  def FingirDeMorto(self):
    print("Fingir de Morto ")
  
  def Rolar(self):
    print("Rolar")



Cachorro2 = Cachorro_Adrestado("toto","bitbull")

print(Cachorro2.getNome())
print(Cachorro2.getRaca())
Cachorro2.Deitar()
Cachorro2.Rolar()
Cachorro2.FingirDeMorto()

Cacho=Cachorro("Thor", "Rottweiler")


print(Cacho.getNome())
print(Cacho.getRaca())